### ISSUE TITLE
Include --advertise-exit-node

### ISSUE THREAD

**Issue by mraczka** [ivokub/tailscale-qpkg#15]
Is there any way to use [--advertise-exit-node](https://tailscale.com/kb/1103/exit-nodes) flag? I've tried edit the startup script (v1.6) but it didn't work.

**Comment by ivokub** [comment]
Yes, there is. There is no need to change the startup script, as it handles the Tailscale daemon (tailscaled), but the network configuration is handled by the Tailscale client (tailscale).

In order to advertise as an exit node, run:
* `getcfg SHARE_DEF defVolMP -f /etc/config/def_share.info` to get Tailscale installation location (for example `/share/CE_CACHEDEV1_DATA/`)
* `cd /share/CE_CACHEDEV1_DATA/.qpkg/Tailscale` to go to Tailscale installation directory
* `./tailscale -socket var/run/tailscale/tailscaled.sock up --advertise-exit-node` to reconfigure Tailscale to act as an exit node.

That is all. I can confirm that the option works and my QNAP routes the traffic well.

**Comment by takotakot** [comment]
The command may have been changed. 

```
1.36.0
  tailscale commit: 96f6580381ac0c01122e77cff79f01baa678d6a4
  other commit: 49bd4454362e6e52fe8c86ad51b3734dd83d764c
  go version: go1.19.4-tsdc0ce6324d
```

```
./tailscale -socket /tmp/tailscale/tailscaled.sock up --advertise-exit-node --accept-routes
```

works for me.
