### ISSUE TITLE
tailscale uses incorrect path for tailscaled.sock (absolute instead of relative)

### ISSUE THREAD

**Issue by pmcjones** [ivokub/tailscale-qpkg#25]
Example:

[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # uname -a
Linux XXXX-ts451 4.14.24-qnap #1 SMP Mon Jul 26 01:49:01 CST 2021 x86_64 GNU/Linux
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # ./tailscale version
1.14.0
  tailscale commit: 62a458f7f4474ac2e26676ed8f06d43e80e5a34a
  go version: go1.17
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # ./tailscale ping
Failed to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)

**Comment by pmcjones** [comment]
Should the tailscale command be changed to reference var/run/tailscale/tailscaled.sock (relative pathname) instead of /var/run/tailscale/tailscaled.sock? I just added a symbolic link from /var/run/talescale to /share/CACHEDEV1_DATA/.qpkg/Tailscale/var/run/tailscale/, and now I can execute commands. But I assume after I reboot the QNAP I'll have to reinstall that link.

**Comment by ivokub** [comment]
Because the root filesystem is overwritten on every firmware update, then the installation script does not use `/var/run/tailscale/tailscaled.sock` for the socket, but instead uses the local path.

Instead of creating a symlink, you can append `-socket` option to the `tailscale` command with the location of the UNIX socket. This is also documented in the readme.
