### ISSUE TITLE
There is no Digital signature

### ISSUE THREAD

**Issue by Drallas** [ivokub/tailscale-qpkg#26]
I'm suddenly seeing a "There is no Digital signature" warning. I think it has something to do with QTS 5.0 I just installed?!

![Screenshot 2021-10-05 at 14 33 24](https://user-images.githubusercontent.com/24792888/136038830-b1031e92-a33e-478b-bc36-0e4729d29c0c.png)

![Screenshot 2021-10-05 at 16 03 04](https://user-images.githubusercontent.com/24792888/136039247-99935b16-560a-4532-bf8d-e5e7f4d5123f.png)

**Comment by ivokub** [comment]
Thanks for the feedback, @Drallas.

The packages have never been signed digitally and corresponding notice has been displayed in the App Center also for lower QTS versions. It seems that there is a new "Security Counselor" feature, which makes the warning more prominent.

At least for QTS 4.5, the lack of digital signature has not prevented Tailscale to function properly. Is it fully functional also on 5.0 otherwise? My QNAP is quite far away and Tailscale tunnel is the only way to access it, so I can not really test it myself.

I have not bothered looking into signing the package digitally as I have expected that the official Tailscale package would arrive soon, but it does not seem to have yet.

**Comment by talios** [comment]
Tailscale has been working flawlessly for me under QTS 5.0 so far - altho I've recently hit some DNS issues which I'm not yet sure if they're related to Tailscale or not ( literally just discovered the DNS issue as the cause of another issue I was trying to work ).

Likewise, I'm currently 6 hours drive away from my QNAP (and crazily did the 4.5 -> 5.0 upgrade remotely - was glad to see Tailscale startup flawlessly and I was back and running/acccess the server within 30 minutes or so.

**Comment by ivokub** [comment]
> Tailscale has been working flawlessly for me under QTS 5.0 so far - altho I've recently hit some DNS issues which I'm not yet sure if they're related to Tailscale or not ( literally just discovered the DNS issue as the cause of another issue I was trying to work ).
> 
> Likewise, I'm currently 6 hours drive away from my QNAP (and crazily did the 4.5 -> 5.0 upgrade remotely - was glad to see Tailscale startup flawlessly and I was back and running/acccess the server within 30 minutes or so.

I took the risk and upgraded my QNAP and it came online without problems. For me it also seems that Tailscale works great on QTS 5.0.

If it seems that the problems with DNS seem to be related to Tailscale package, then could you open a new issue? I would look into it separately then (probably by using a VM instance of QTS).

**Comment by talios** [comment]
> If it seems that the problems with DNS seem to be related to Tailscale package, then could you open a new issue? I would look into it separately then (probably by using a VM instance of QTS).

Note there was a newer QTS firmware released that specifically called out fixing DNS issues. I've not had any issues with Tailscale and DNS since updating...

**Comment by ivokub** [comment]
> > If it seems that the problems with DNS seem to be related to Tailscale package, then could you open a new issue? I would look into it separately then (probably by using a VM instance of QTS).
> 
> Note there was a newer QTS firmware released that specifically called out fixing DNS issues. I've not had any issues with Tailscale and DNS since updating...

Great! Thanks for confirming.
